name: Deploy Website via SSH

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_NEW }}

    - name: Add server to known_hosts
      run: ssh-keyscan 13.250.121.227 >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no root@13.250.121.227 'echo "SSH connection successful"'

    - name: Copy files via SCP
      run: scp -r ./* root@13.250.121.227:/www/wwwroot/eranga.run.place

    - name: Verify deployment
      run: ssh root@13.250.121.227 'ls -l /www/wwwroot/eranga.run.place'
