name: Deploy Website via SSH

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: ssh-keyscan 18.142.228.150 >> ~/.ssh/known_hosts

    - name: Copy files via SCP
      run: scp -r ./* root@18.142.228.150:/www/wwwroot/eranga.run.place

    - name: Verify deployment
      run: ssh root@18.142.228.150 'ls -l /www/wwwroot/eranga.run.place'
